s = set()
n1 = int(input("Enter the number :"))
s.add(n1)
n1 = int(input("Enter the number :"))
s.add(n1)
n1 = int(input("Enter the number :"))
s.add(n1)
n1 = int(input("Enter the number :"))
s.add(n1)
n1 = int(input("Enter the number :"))
s.add(n1)
n1 = int(input("Enter the number :"))
s.add(n1) 
n1 = int(input("Enter the number :"))
s.add(n1)
n1 = int(input("Enter the number :"))
s.add(n1)
print(s)
print(s)
print(s)
print(s)

